# -----------------------------------------------------
# Custom Kitty Configuration
# -----------------------------------------------------

# Historial gigante para no perder ni un solo log 
scrollback_lines 50000

# Ocultar el puntero del mouse al escribir para que no estorbe la lectura
mouse_hide_wait 2.0

# Copiar al portapapeles automáticamente al seleccionar texto
copy_on_select yes

# Estilo de pestañas (tabs) moderno (útil si abres múltiples consolas con Ctrl+Shift+T)
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}: {title}"

# Opacidad: 0.7 a veces es muy transparente y cansa la vista al leer código. 
# 0.85 mantiene el efecto cristal pero da mejor contraste.
background_opacity 0.7

# Un poco más de aire a los lados del texto
window_padding_width 12
